from pathlib import Path
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)
from reportlab.lib.units import inch

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    PageBreak
)

PRIMARY = colors.HexColor("#5B4BDB")
LIGHT = colors.HexColor("#ECEBFF")
SUCCESS = colors.HexColor("#2E7D32")
WARNING = colors.HexColor("#F9A825")
ERROR = colors.HexColor("#C62828")
GRAY = colors.HexColor("#666666")

def create_styles():

    styles = getSampleStyleSheet()

    styles.add(

        ParagraphStyle(

            name="CoverTitle",

            fontName="Helvetica-Bold",

            fontSize=26,

            alignment=TA_CENTER,

            textColor=PRIMARY,

            leading=32,
            spaceAfter=18

        )

    )

    styles.add(

        ParagraphStyle(

            name="CoverSubTitle",

            fontName="Helvetica",

            fontSize=15,

            alignment=TA_CENTER,

            textColor=GRAY,

            spaceAfter=20

        )

    )

    styles.add(

        ParagraphStyle(

            name="Heading",

            fontName="Helvetica-Bold",

            fontSize=17,

            textColor=PRIMARY,

            spaceAfter=12

        )

    )

    styles.add(

        ParagraphStyle(

            name="SubHeading",

            fontName="Helvetica-Bold",

            fontSize=13,

            textColor=PRIMARY,

            spaceAfter=8

        )

    )

    styles.add(

        ParagraphStyle(

            name="NormalText",

            fontName="Helvetica",

            fontSize=10,

            leading=18

        )

    )

    return styles

def add_footer(story, styles):

    story.append(Spacer(1,0.40*inch))

    story.append(

        HRFlowable(

            width="100%",

            color=PRIMARY

        )

    )

    story.append(

        Paragraph(

            f"Generated by BookForge • {datetime.now().strftime('%d %B %Y %I:%M %p')}",

            styles["NormalText"]

        )

    )

def add_cover_page(story, styles, report_data):

    summary = report_data["summary"]

    book = report_data["book"]

    story.append(

        HRFlowable(

            width="100%",

            color=PRIMARY

        )

    )

    story.append(Spacer(1,0.25*inch))

    story.append(
        Paragraph(
            "BOOKFORGE",
            styles["CoverTitle"]
        )
    )

    story.append(
        Spacer(1, 0.08 * inch)
    )

    story.append(
        Paragraph(
            "EPUB QUALITY REPORT",
            styles["CoverSubTitle"]
        )
    )

    story.append(

            HRFlowable(

                width="100%",

                color=PRIMARY

            )

    )

    story.append(Spacer(1,0.45*inch))

    generated = datetime.now().strftime(

        "%d %B %Y %I:%M %p"

    )

    data = [

        ["Book", book.get("title","N/A")],

        ["Author", book.get("author","N/A")],

        ["Generated", generated],

        [

            "Overall Score",

            f"{summary.get('overall_score',0)}/100"

        ],

        [

            "Grade",

            summary.get("grade","-")

        ],

        [

            "Status",

            summary.get("status","-")

        ]

    ]

    table = Table(

        data,

        colWidths=[2.2*inch,4*inch]

    )

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(0,-1),LIGHT),

            ("TEXTCOLOR",(0,0),(0,-1),PRIMARY),

            ("FONTNAME",(0,0),(0,-1),"Helvetica-Bold"),

            ("GRID",(0,0),(-1,-1),0.4,colors.grey),

            ("BOTTOMPADDING",(0,0),(-1,-1),10),

            ("TOPPADDING",(0,0),(-1,-1),10)

        ])

    )

    story.append(table)

    add_footer(story,styles)

    story.append(PageBreak())

def add_executive_summary(story, styles, report_data):

    story.append(
        Paragraph(
            "Executive Summary",
            styles["Heading"]
        )
    )

    summary = report_data.get("summary", {})
    quality = report_data.get("quality", {})
    statistics = report_data.get("statistics", {})

    # ===========================================
    # Overall Summary
    # ===========================================

    summary_table = Table([

        ["Metric", "Value"],

        ["Overall Score", f"{summary.get('overall_score',0)} / 100"],

        ["Grade", summary.get("grade","N/A")],

        ["Status", summary.get("status","N/A")]

    ], colWidths=[2.6*inch,3.2*inch])

    summary_table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),PRIMARY),

        ("TEXTCOLOR",(0,0),(-1,0),colors.white),

        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

        ("GRID",(0,0),(-1,-1),0.4,colors.grey),

        ("BACKGROUND",(0,1),(0,-1),LIGHT),

        ("BOTTOMPADDING",(0,0),(-1,-1),8),

        ("TOPPADDING",(0,0),(-1,-1),8)

    ]))

    story.append(summary_table)

    story.append(Spacer(1,0.35*inch))

    # ===========================================
    # Quality Summary
    # ===========================================

    story.append(

        Paragraph(

            "Quality Summary",

            styles["Heading"]

        )

    )

    quality_rows = [

        ["Component","Score"],

        ["Metadata",f"{quality.get('metadata',0)}%"],

        ["HTML",f"{quality.get('html',0)}%"],

        ["CSS",f"{quality.get('css',0)}%"],

        ["Images",f"{quality.get('images',0)}%"],

        ["Hyperlinks",f"{quality.get('hyperlinks',0)}%"]

    ]

    quality_table = Table(

        quality_rows,

        colWidths=[3.5*inch,1.5*inch]

    )

    quality_table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),PRIMARY),

        ("TEXTCOLOR",(0,0),(-1,0),colors.white),

        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

        ("GRID",(0,0),(-1,-1),0.4,colors.grey),

        ("ALIGN",(1,1),(-1,-1),"CENTER"),

        ("BOTTOMPADDING",(0,0),(-1,-1),8),

        ("TOPPADDING",(0,0),(-1,-1),8)

    ]))

    story.append(quality_table)

    story.append(Spacer(1,0.35*inch))

    # ===========================================
    # Book Statistics
    # ===========================================

    story.append(

        Paragraph(

            "Book Statistics",

            styles["Heading"]

        )

    )

    statistics_table = Table([

        ["Statistic","Value"],

        ["Chapters",str(statistics.get("chapters",0))],

        ["Images",str(statistics.get("images",0))],

        ["Stylesheets",str(statistics.get("stylesheets",0))],

        ["Hyperlinks",str(statistics.get("hyperlinks",0))],

        ["Page Types",str(statistics.get("page_types",0))]

    ], colWidths=[3.5*inch,1.5*inch])

    statistics_table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),PRIMARY),

        ("TEXTCOLOR",(0,0),(-1,0),colors.white),

        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

        ("GRID",(0,0),(-1,-1),0.4,colors.grey),

        ("ALIGN",(1,1),(-1,-1),"CENTER"),

        ("BOTTOMPADDING",(0,0),(-1,-1),8),

        ("TOPPADDING",(0,0),(-1,-1),8)

    ]))

    story.append(statistics_table)

    add_footer(story, styles)

    story.append(PageBreak())

def collect_unique_issues(report_data):

    grouped = {
        "critical": {},
        "warnings": {},
        "information": {}
    }

    def add_issue(category, issue, chapter=None):

        message = issue.get("message", "").strip()

        if not message:
            return

        if message not in grouped[category]:

            grouped[category][message] = {

                "message": message,

                "severity": issue.get("severity", ""),

                "rule": issue.get(
                    "rule",
                    issue.get("field", "")
                ),

                # Store chapter names instead of count
                "chapters": set()

            }

        # Add chapter name
        if chapter:
            grouped[category][message]["chapters"].add(chapter)

    # ======================================
    # Global Issues (Metadata/CSS/etc.)
    # ======================================

    issues = report_data.get("issues", {})

    for issue in issues.get("critical", []):
        add_issue("critical", issue)

    for issue in issues.get("warnings", []):
        add_issue("warnings", issue)

    for issue in issues.get("information", []):
        add_issue("information", issue)

    # ======================================
    # Chapter Issues
    # ======================================

    for chapter in report_data.get("chapters", []):

        chapter_name = chapter.get(
            "chapter",
            "Unknown"
        )

        for issue in chapter.get("issues", []):

            severity = issue.get(
                "severity",
                "INFO"
            )

            if severity == "ERROR":

                add_issue(
                    "critical",
                    issue,
                    chapter_name
                )

            elif severity == "WARNING":

                add_issue(
                    "warnings",
                    issue,
                    chapter_name
                )

            else:

                add_issue(
                    "information",
                    issue,
                    chapter_name
                )

    # ======================================
    # Convert set → count
    # ======================================

    for category in grouped.values():

        for issue in category.values():

            issue["count"] = len(
                issue["chapters"]
            )

            issue["chapter_list"] = sorted(
                issue["chapters"]
            )

    return grouped

def add_issues_page(story, styles, report_data):

    story.append(
        Paragraph(
            "Issues Summary",
            styles["Heading"]
        )
    )

    grouped = collect_unique_issues(report_data)

    critical = list(grouped["critical"].values())
    warnings = list(grouped["warnings"].values())
    information = list(grouped["information"].values())

    # =====================================
    # Summary
    # =====================================

    summary_table = Table([

        ["Severity", "Unique Issues"],

        ["Critical", str(len(critical))],

        ["Warnings", str(len(warnings))],

        ["Information", str(len(information))]

    ], colWidths=[3.5 * inch, 1.5 * inch])

    summary_table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),PRIMARY),

        ("TEXTCOLOR",(0,0),(-1,0),colors.white),

        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

        ("GRID",(0,0),(-1,-1),0.4,colors.grey),

        ("BACKGROUND",(0,1),(0,-1),LIGHT),

        ("ALIGN",(1,1),(-1,-1),"CENTER"),

        ("BOTTOMPADDING",(0,0),(-1,-1),8),

        ("TOPPADDING",(0,0),(-1,-1),8)

    ]))

    story.append(summary_table)

    story.append(Spacer(1,0.30*inch))

    # =====================================
    # Critical Issues
    # =====================================

    story.append(
        Paragraph(
            "Critical Issues",
            styles["SubHeading"]
        )
    )

    if not critical:

        story.append(
            Paragraph(
                "No critical issues found.",
                styles["NormalText"]
            )
        )

    else:

        rows = [["Issue", "Affected Chapters"]]

        for issue in critical:

            rows.append([

                issue["message"],

                f"{issue['count']} chapter(s)"

            ])

        table = Table(
            rows,
            colWidths=[5.2*inch,1.2*inch]
        )

        table.setStyle(TableStyle([

            ("BACKGROUND",(0,0),(-1,0),PRIMARY),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

            ("GRID",(0,0),(-1,-1),0.3,colors.grey),

            ("BOTTOMPADDING",(0,0),(-1,-1),7),

            ("TOPPADDING",(0,0),(-1,-1),7)

        ]))

        story.append(table)

    story.append(Spacer(1,0.30*inch))

    # =====================================
    # Warnings
    # =====================================

    story.append(
        Paragraph(
            "Warnings",
            styles["SubHeading"]
        )
    )

    if not warnings:

        story.append(
            Paragraph(
                "No warnings found.",
                styles["NormalText"]
            )
        )

    else:

        rows = [["Issue", "Affected Chapters"]]

        for issue in warnings:

            rows.append([

                issue["message"],

                str(issue["count"])

            ])

        table = Table(
            rows,
            colWidths=[5.2*inch,1.2*inch]
        )

        table.setStyle(TableStyle([

            ("BACKGROUND",(0,0),(-1,0),PRIMARY),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

            ("GRID",(0,0),(-1,-1),0.3,colors.grey),

            ("BOTTOMPADDING",(0,0),(-1,-1),7),

            ("TOPPADDING",(0,0),(-1,-1),7)

        ]))

        story.append(table)

    story.append(Spacer(1,0.30*inch))

    # =====================================
    # Information
    # =====================================

    if information:

        story.append(
            Paragraph(
                "Information",
                styles["SubHeading"]
            )
        )

        rows = [["Issue", "Affected Chapters"]]

        for issue in information:

            rows.append([

                issue["message"],

                str(issue["count"])

            ])

        table = Table(
            rows,
            colWidths=[5.2*inch,1.2*inch]
        )

        table.setStyle(TableStyle([

            ("BACKGROUND",(0,0),(-1,0),PRIMARY),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

            ("GRID",(0,0),(-1,-1),0.3,colors.grey),

            ("BOTTOMPADDING",(0,0),(-1,-1),7),

            ("TOPPADDING",(0,0),(-1,-1),7)

        ]))

        story.append(table)

    add_footer(story, styles)

    story.append(PageBreak())

def add_chapter_summary(story, styles, report_data):

    story.append(
        Paragraph(
            "Chapter Analysis Summary",
            styles["Heading"]
        )
    )

    chapters = report_data.get("chapters", [])

    rows = [[
        "Chapter",
        "Score",
        "Status",
        "Issues"
    ]]

    for chapter in chapters:

        rows.append([

            chapter.get("chapter", ""),

            str(chapter.get("score", 0)),

            chapter.get("status", ""),

            str(len(chapter.get("issues", [])))

        ])

    table = Table(
        rows,
        colWidths=[
            2.9*inch,
            0.8*inch,
            1.1*inch,
            0.8*inch
        ]
    )

    table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),PRIMARY),

        ("TEXTCOLOR",(0,0),(-1,0),colors.white),

        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

        ("GRID",(0,0),(-1,-1),0.3,colors.grey),

        ("ALIGN",(1,1),(-1,-1),"CENTER"),

        ("BOTTOMPADDING",(0,0),(-1,-1),6),

        ("TOPPADDING",(0,0),(-1,-1),6)

    ]))

    story.append(table)

    add_footer(story, styles)

    story.append(PageBreak())



def add_detailed_chapter_analysis(story, styles, report_data):

    story.append(
        Paragraph(
            "Detailed Chapter Analysis",
            styles["Heading"]
        )
    )

    chapters = report_data.get("chapters", [])

    if not chapters:

        story.append(
            Paragraph(
                "No chapter analysis available.",
                styles["NormalText"]
            )
        )

        add_footer(story, styles)
        story.append(PageBreak())
        return

    for chapter in chapters:

        chapter_name = chapter.get("chapter", "Unknown Chapter")
        score = chapter.get("score", 0)
        status = chapter.get("status", "PASS")
        issues = chapter.get("issues", [])

        # Skip chapters without problems
        if status == "PASS":
            continue

        # Status color
        if status == "WARNING":
            status_color = WARNING
        else:
            status_color = ERROR

        story.append(
            Paragraph(
                f"<b>{chapter_name}</b>",
                styles["SubHeading"]
            )
        )

        info_table = Table(
            [
                ["Score", f"{score}/100"],
                ["Status", status],
                ["Issues", str(len(issues))]
            ],
            colWidths=[2.2 * inch, 3.5 * inch]
        )

        info_table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ("BACKGROUND", (0, 0), (0, -1), LIGHT),
            ("TEXTCOLOR", (0, 0), (0, -1), PRIMARY),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("TEXTCOLOR", (1, 1), (1, 1), status_color),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8)
        ]))

        story.append(info_table)

        story.append(Spacer(1, 0.12 * inch))

        if issues:

            issue_rows = [
                ["Severity", "Rule", "Message"]
            ]

            for issue in issues:

                issue_rows.append([
                    issue.get("severity", ""),
                    issue.get("rule", issue.get("field", "")),
                    issue.get("message", "")
                ])

            issue_table = Table(
                issue_rows,
                colWidths=[
                    1.1 * inch,
                    1.5 * inch,
                    3.6 * inch
                ]
            )

            issue_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6)
            ]))

            story.append(issue_table)

        else:

            story.append(
                Paragraph(
                    "<font color='green'>No issues found.</font>",
                    styles["NormalText"]
                )
            )

        story.append(Spacer(1, 0.35 * inch))

    add_footer(story, styles)
    story.append(PageBreak())

def add_recommendations_page(story, styles, report_data):

    story.append(
        Paragraph(
            "Recommendations",
            styles["Heading"]
        )
    )

    recommendations = report_data.get("recommendations", [])

    if not recommendations:

        story.append(
            Paragraph(
                "Congratulations! No recommendations. The EPUB meets all quality requirements.",
                styles["NormalText"]
            )
        )

    else:

        story.append(
            Paragraph(
                "The following improvements are recommended to increase the EPUB quality:",
                styles["NormalText"]
            )
        )

        story.append(Spacer(1, 0.20 * inch))

        rows = [["#", "Recommendation"]]

        for index, recommendation in enumerate(recommendations, start=1):

            rows.append([
                str(index),
                recommendation
            ])

        table = Table(
            rows,
            colWidths=[0.5 * inch, 5.8 * inch]
        )

        table.setStyle(TableStyle([

            ("BACKGROUND", (0,0), (-1,0), PRIMARY),

            ("TEXTCOLOR", (0,0), (-1,0), colors.white),

            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

            ("GRID", (0,0), (-1,-1), 0.3, colors.grey),

            ("BACKGROUND", (0,1), (0,-1), LIGHT),

            ("FONTNAME", (0,1), (0,-1), "Helvetica-Bold"),

            ("VALIGN", (0,0), (-1,-1), "TOP"),

            ("BOTTOMPADDING", (0,0), (-1,-1), 8),

            ("TOPPADDING", (0,0), (-1,-1), 8)

        ]))

        story.append(table)

    story.append(Spacer(1,0.35*inch))

    story.append(
        Paragraph(
            "<b>Final Remarks</b>",
            styles["SubHeading"]
        )
    )

    score = report_data.get("summary", {}).get("overall_score", 0)

    if score >= 90:

        remarks = (
            "Excellent EPUB. It is production-ready and follows most quality guidelines."
        )

    elif score >= 80:

        remarks = (
            "Good EPUB with only minor improvements required before publishing."
        )

    elif score >= 70:

        remarks = (
            "The EPUB is usable but should be reviewed to improve quality."
        )

    elif score >= 60:

        remarks = (
            "Several quality issues should be fixed before publication."
        )

    else:

        remarks = (
            "This EPUB requires significant improvements before it is ready for release."
        )

    story.append(
        Paragraph(
            remarks,
            styles["NormalText"]
        )
    )

    story.append(Spacer(1,0.5*inch))

    story.append(
        Paragraph(
            "<font color='#5B4BDB'><b>Thank you for using BookForge.</b></font>",
            styles["Heading"]
        )
    )

    add_footer(story, styles)


def generate_pdf(report_data, output_path: Path):
    """
    Generate the complete BookForge PDF report.
    """

    styles = create_styles()

    doc = SimpleDocTemplate(
        str(output_path),
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    story = []

    # ----------------------------------
    # Cover Page
    # ----------------------------------
    add_cover_page(
        story,
        styles,
        report_data
    )

    # ----------------------------------
    # Executive Summary
    # ----------------------------------
    add_executive_summary(
        story,
        styles,
        report_data
    )

    add_issues_page(
    story,
    styles,
    report_data
    )

    add_chapter_summary(
    story,
    styles,
    report_data
    )

    add_detailed_chapter_analysis(
        story,
        styles,
        report_data
    )

    add_recommendations_page(
    story,
    styles,
    report_data
    )

    # ----------------------------------
    # Build PDF
    # ----------------------------------
    doc.build(story)

    return output_path